#!/usr/bin/env bash
# rotate-tokens.sh — ISO 27001 A.8.7 token rotation helper
set -euo pipefail

echo "=== Token Rotation Helper ==="
echo ""
echo "This script assists with rotating JWT signing keys and service tokens."
echo ""
echo "Manual steps required:"
echo ""
echo "1. Generate new JWT signing key pair:"
echo "   openssl genrsa -out private_key_new.pem 4096"
echo "   openssl rsa -in private_key_new.pem -pubout -out public_key_new.pem"
echo ""
echo "2. Update JOL_MCP_JWT_PUBLIC_KEY environment variable in all servers"
echo ""
echo "3. Revoke old tokens by adding their JTIs to the revocation list"
echo ""
echo "4. Restart all MCP servers with new key"
echo ""
echo "5. Verify new tokens work:"
echo "   make test"
echo ""
echo "6. Remove old key after grace period (recommended: 24 hours)"
echo ""
echo "=== Rotation checklist ==="
echo "[ ] New key pair generated"
echo "[ ] Public key updated in all server configs"
echo "[ ] Old tokens added to revocation list"
echo "[ ] All servers restarted"
echo "[ ] Integration tests pass with new tokens"
echo "[ ] Old key scheduled for removal"
echo "[ ] Rotation logged in change management system"
